update to current version

diff --git a/.github/workflows/ej-issue.yml b/.github/workflows/ej-issue.yml
--- a/.github/workflows/ej-issue.yml
+++ b/.github/workflows/ej-issue.yml
@@ -198,9 +198,8 @@ jobs:
             git config --global user.email 'junie-eap[bot]@users.noreply.github.com'
 
             chmod +x ./junie.sh 
-            /bin/sh ./junie.sh --output-format=json --json-output-file=result.json --flags=cloud-logger
-
-
+            /bin/sh ./junie.sh --output-format=json --json-output-file=$JUNIE_WORK_TEMP/.matterhorn/result.json --flags=cloud-logger
+            cp  $HOME/.junie/logs/junie.log $JUNIE_WORK_TEMP/.matterhorn/ || echo "No junie.log"
       - name: Check if junie run failed
         if: failure() && (hashFiles('.devcontainer/devcontainer.json') != '')
         run: |
@@ -216,7 +215,6 @@ jobs:
           mkdir -p .junie-upload
 
           docker cp "$CONTAINER_ID":"/tmp/junie-work/.matterhorn" .junie-upload/.matterhorn || echo "No .matterhorn"
-          docker cp "$CONTAINER_ID":"/tmp/junie-work/idea-logs/log/idea.log" .junie-upload/.matterhorn/idea.log || echo "No idea-logs"          
           sudo chown -R runner:runner ${{ github.workspace }} || true
 
           # rename containerError.md to executionError.md if main.log exists (aka execution took place)
@@ -278,27 +276,18 @@ jobs:
           export JUNIE_IDE_VERSION="${{ steps.workflow-params.outputs.junie_ide_version }}"
 
           sudo chmod +x ./junie.sh
-          echo "Before running junie.sh"
-          ls -al
-          /bin/sh ./junie.sh  --output-format=json --json-output-file=$JUNIE_WORK_TEMP/result.json --flags=cloud-logger
-          echo "After running junie.sh"
-          ls -al
+          /bin/sh ./junie.sh --output-format=json --json-output-file=$JUNIE_WORK_TEMP/.matterhorn/result.json --flags=cloud-logger || echo "Junie failed"
+          cp -r $HOME/.junie/logs/junie.log $JUNIE_WORK_TEMP/.matterhorn/ || echo "No junie.log"
+          if [ ! -e "$JUNIE_WORK_TEMP/.matterhorn/result.json" ]; then echo "No result.json"; fi
 
       - name: Extracting .idea and ej-logs for non-container run
         if: always() && (hashFiles('.devcontainer/devcontainer.json') == '')
         run: |
           echo "Copying logs to target dir..."
-          ls -al /tmp/junie-work
-          echo "listing .matterhorn"
-          ls -al /tmp/junie-work/.matterhorn
-          ls -al $HOME/.junie/
-          ls -al $HOME/.junie/logs
           sudo chown -R runner:runner /tmp/junie-work
           sudo chown -R runner:runner ${{ github.workspace }} || true
           mkdir .junie-upload
           cp -r /tmp/junie-work/.matterhorn .junie-upload/.matterhorn || echo "No .matterhorn"
-          cp -r $HOME/.junie/logs/junie.log .junie-upload/.matterhorn/ || echo "No junie.log"
-          cp -r /tmp/junie-work/result.json .junie-upload/.matterhorn/ || echo "No result.json"
 
       - name: Save junie result summary
         id: junie_summary
